name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Configure npm registry
      run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

    - uses: c-hive/gha-yarn-cache@v1

    - name: Install dependencies
      run: yarn

    - name: Bootstrap
      run: yarn bootstrap

    - name: Lint
      run: yarn lint
